<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="6">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="783" startPos="158" endPos="158" selMode="0" offset="0" wrapCount="1" lang="CSS" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\home.css" backupFilePath="" originalFileLastModifTimestamp="979648971" originalFileLastModifTimestampHigh="31218615" tabColourId="-1" RTL="no" tabPinned="yes" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1135" startPos="2189" endPos="1807" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\Homepage.html" backupFilePath="" originalFileLastModifTimestamp="1971855192" originalFileLastModifTimestampHigh="31218818" tabColourId="-1" RTL="no" tabPinned="yes" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="37" xOffset="0" scrollWidth="4527" startPos="1683" endPos="1663" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\offer.html" backupFilePath="" originalFileLastModifTimestamp="-311187020" originalFileLastModifTimestampHigh="31218809" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="186" xOffset="0" scrollWidth="639" startPos="1381" endPos="1381" selMode="0" offset="0" wrapCount="1" lang="CSS" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\offerings.css" backupFilePath="" originalFileLastModifTimestamp="1523767930" originalFileLastModifTimestampHigh="31218617" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="2327" startPos="512" endPos="512" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\About.html" backupFilePath="" originalFileLastModifTimestamp="1769912994" originalFileLastModifTimestampHigh="31218646" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="25" xOffset="0" scrollWidth="951" startPos="1872" endPos="1872" selMode="0" offset="0" wrapCount="1" lang="CSS" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\about.css" backupFilePath="" originalFileLastModifTimestamp="1700544397" originalFileLastModifTimestampHigh="31218638" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no">
                <Mark line="47" />
            </File>
            <File firstVisibleLine="68" xOffset="0" scrollWidth="1775" startPos="4138" endPos="4138" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\uses.html" backupFilePath="" originalFileLastModifTimestamp="1009511594" originalFileLastModifTimestampHigh="31218849" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="78" xOffset="0" scrollWidth="959" startPos="1864" endPos="1864" selMode="0" offset="0" wrapCount="1" lang="CSS" encoding="-1" userReadOnly="no" filename="C:\Users\us\Documents\Ice Website\uses.css" backupFilePath="" originalFileLastModifTimestamp="-1929040933" originalFileLastModifTimestampHigh="31218849" tabColourId="-1" RTL="no" tabPinned="no" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
